
"""
DefaultDirAgent Agent

Generated by OpenAI Agents Enterprise CLI
"""

from agents import Agent
from pydantic import BaseModel


class DefaultDirAgentContext(BaseModel):
    """Context model for DefaultDirAgent."""
    # Add context fields specific to this agent
    pass


# TODO: Implement tools
# TODO: Implement guardrails
# TODO: Implement agent instructions


defaultdiragent_agent = Agent[
    DefaultDirAgentContext
](
    name="DefaultDirAgent",
    model="gpt-4.1",
    handoff_description=(
        "{description or 'Handles ' + agent_name.lower() + ' related tasks'}"
    ),
    instructions=(
        "You are DefaultDirAgent. {description or 'A helpful AI agent.'}"
    ),
    tools=[],  # Add tools here
    input_guardrails=[]  # Add guardrails here
)
