#!/usr/bin/env python3
"""
OpenAI Agents Enterprise CLI

A comprehensive command-line tool for managing agents, MCP servers,
and enterprise deployments.
"""

import os
import sys
from pathlib import Path
from typing import List

import click

# Add the parent directory to the path so we can import our modules
sys.path.insert(0, str(Path(__file__).parent.parent))


@click.group()
@click.version_option(version="1.0.0")
def cli():
    """OpenAI Agents Enterprise CLI

    Manage agents, MCP servers, and enterprise deployments with ease.
    """
    pass


@cli.group()
def agent():
    """Agent management commands."""
    pass


@agent.command()
@click.argument("agent_name")
@click.option("--description", "-d", help="Agent description")
@click.option("--tools", "-t", multiple=True, help="Tools to include")
@click.option("--guardrails", "-g", multiple=True, help="Guardrails to include")
@click.option("--output-dir", "-o", default="./agents", help="Output directory")
def create(
    agent_name: str,
    description: str,
    tools: List[str],
    guardrails: List[str],
    output_dir: str,
):
    """Create a new agent with boilerplate code."""

    agent_dir = Path(output_dir) / agent_name.lower().replace(" ", "_")
    agent_dir.mkdir(parents=True, exist_ok=True)

    click.echo(f"🤖 Creating agent '{agent_name}'...")

    # Generate agent Python file
    default_handoff = "'Handles ' + agent_name.lower() + ' related tasks'"
    agent_template = f'''
"""
{agent_name} Agent

Generated by OpenAI Agents Enterprise CLI
"""

from agents import Agent, function_tool, input_guardrail, RunContextWrapper
from typing import Optional
from pydantic import BaseModel

class {agent_name.replace(' ', '')}Context(BaseModel):
    """Context model for {agent_name}."""
    # Add context fields specific to this agent
    pass

# TODO: Implement tools
# TODO: Implement guardrails
# TODO: Implement agent instructions

{agent_name.lower().replace(' ', '_')}_agent = Agent[
    {agent_name.replace(' ', '')}Context
](
    name="{agent_name}",
    model="gpt-4.1",
    handoff_description=(
        "{{description or {default_handoff}}}"
    ),
    instructions=(
        "You are {agent_name}. {{description or 'A helpful AI agent.'}}"
    ),
    tools=[],  # Add tools here
    input_guardrails=[]  # Add guardrails here
)
'''

    agent_filename = f"{agent_name.lower().replace(' ', '_')}_agent.py"
    with open(agent_dir / agent_filename, "w") as f:
        f.write(agent_template)

    click.echo(f"✅ Agent '{agent_name}' created in {agent_dir}")
    click.echo("📁 Files created:")
    click.echo("   - " + agent_filename)


@cli.group()
def mcp():
    """MCP server management commands."""
    pass


@mcp.command("create")
@click.argument("server_name")
@click.argument("openapi_spec_file")
@click.option("--base-url", required=True, help="Base URL for the API")
@click.option("--output-dir", "-o", default="./mcp_servers", help="Output directory")
@click.option("--auto-deploy", is_flag=True, help="Auto-deploy after creation")
@click.option("--max-endpoints", default=20, help="Maximum endpoints to include")
@click.option("--max-complexity", default=8, help="Maximum complexity score")
@click.option(
    "--auth-type",
    default="none",
    type=click.Choice(["none", "bearer", "api_key"]),
    help="Authentication type",
)
@click.option("--include-tests", is_flag=True, default=True, help="Include tests")
@click.option("--include-docker", is_flag=True, default=True, help="Include Docker")
def create_server(
    server_name: str,
    openapi_spec_file: str,
    base_url: str,
    output_dir: str,
    auto_deploy: bool,
    max_endpoints: int,
    max_complexity: int,
    auth_type: str,
    include_tests: bool,
    include_docker: bool,
):
    """Create MCP server from OpenAPI specification."""

    if not os.path.exists(openapi_spec_file):
        click.echo(f"❌ OpenAPI spec file not found: {openapi_spec_file}")
        return

    click.echo(f"🔧 Creating MCP server '{server_name}'...")
    click.echo(f"📊 Analyzing OpenAPI spec: {openapi_spec_file}")
    click.echo(f"🌐 Base URL: {base_url}")

    try:
        # Import MCP components
        from mcp.registry import MCPServerRegistry
        from mcp.server_generator import MCPServerGenerator, ServerGenerationConfig

        # Create generation configuration
        config = ServerGenerationConfig(
            server_name=server_name,
            server_description=f"MCP server for {server_name} API",
            package_name=server_name.lower().replace(" ", "_").replace("-", "_"),
            base_url=base_url,
            auth_type=auth_type,
            max_endpoints=max_endpoints,
            max_complexity=max_complexity,
            output_dir=output_dir,
            create_tests=include_tests,
            create_dockerfile=include_docker,
        )

        # Generate the server
        generator = MCPServerGenerator()
        result = generator.generate_server(openapi_spec_file, config)

        if result.success:
            # Write files to disk
            server_path = generator.write_server_to_disk(result, output_dir)

            click.echo(f"✅ MCP server '{server_name}' created successfully!")
            click.echo(f"📁 Server location: {server_path}")
            files_count = result.generation_summary["total_files"]
            endpoints_count = result.generation_summary["selected_endpoints"]
            click.echo(f"📊 Generated {files_count} files")
            click.echo(f"🔧 Included {endpoints_count} endpoints")

            # Display complexity distribution
            complexity = result.generation_summary["complexity_distribution"]
            click.echo("📈 Complexity distribution:")
            click.echo(f"   Simple: {complexity['simple']}")
            click.echo(f"   Moderate: {complexity['moderate']}")
            click.echo(f"   Complex: {complexity['complex']}")

            if auto_deploy:
                click.echo("🚀 Auto-deploying server...")
                try:
                    import asyncio

                    # Read the OpenAPI spec for registry
                    with open(openapi_spec_file, "r") as f:
                        openapi_spec = f.read()

                    registry = MCPServerRegistry()
                    server_id = server_name.lower().replace(" ", "_")

                    # Use async method properly
                    asyncio.run(
                        registry.register_server(
                            server_id=server_id,
                            name=server_name,
                            openapi_spec=openapi_spec,
                            config=config,
                            description=f"Auto-deployed {server_name} server",
                            auto_generate=False,  # Already generated
                        )
                    )
                    click.echo("✅ Server registered and deployed!")
                except Exception as e:
                    click.echo(f"⚠️  Server created but deployment failed: {e}")
        else:
            click.echo("❌ Server generation failed:")
            for error in result.errors:
                click.echo(f"   • {error}")

    except ImportError as e:
        click.echo(f"❌ Missing dependencies: {e}")
        click.echo("💡 Make sure MCP components are installed")
    except Exception as e:
        click.echo(f"❌ Server generation failed: {e}")


@mcp.command("list")
def list_servers():
    """List all registered MCP servers."""
    try:
        from mcp.registry import MCPServerRegistry

        registry = MCPServerRegistry()
        servers = registry.list_servers()

        if not servers:
            click.echo("📭 No MCP servers registered")
            return

        click.echo(f"📋 Found {len(servers)} MCP servers:")
        click.echo()

        for server in servers:
            status_emoji = {
                "created": "🆕",
                "generating": "⚙️",
                "generated": "✅",
                "running": "🟢",
                "stopped": "🔴",
                "error": "❌",
            }.get(server.status.value, "❓")

            click.echo(f"{status_emoji} {server.name} ({server.id})")
            click.echo(f"   Status: {server.status.value}")
            click.echo(f"   Endpoints: {server.endpoint_count}")
            click.echo(f"   Created: {server.created_at.strftime('%Y-%m-%d %H:%M')}")
            if server.server_path:
                click.echo(f"   Path: {server.server_path}")
            click.echo()

    except Exception as e:
        click.echo(f"❌ Failed to list servers: {e}")


@mcp.command("start")
@click.argument("server_id")
def start_server(server_id: str):
    """Start a registered MCP server."""
    try:
        import asyncio

        from mcp.registry import MCPServerRegistry

        registry = MCPServerRegistry()

        click.echo(f"🚀 Starting MCP server '{server_id}'...")
        success = asyncio.run(registry.start_server(server_id))

        if success:
            click.echo(f"✅ Server '{server_id}' started successfully!")
        else:
            click.echo(f"❌ Failed to start server '{server_id}'")

    except Exception as e:
        click.echo(f"❌ Failed to start server: {e}")


@mcp.command("stop")
@click.argument("server_id")
def stop_server(server_id: str):
    """Stop a running MCP server."""
    try:
        import asyncio

        from mcp.registry import MCPServerRegistry

        registry = MCPServerRegistry()

        click.echo(f"🛑 Stopping MCP server '{server_id}'...")
        success = asyncio.run(registry.stop_server(server_id))

        if success:
            click.echo(f"✅ Server '{server_id}' stopped successfully!")
        else:
            click.echo(f"❌ Failed to stop server '{server_id}'")

    except Exception as e:
        click.echo(f"❌ Failed to stop server: {e}")


@mcp.command("status")
@click.argument("server_id")
def server_status(server_id: str):
    """Check status of a specific MCP server."""
    try:
        import asyncio

        from mcp.registry import MCPServerRegistry

        registry = MCPServerRegistry()

        # Get server info
        server = registry.get_server(server_id)
        if not server:
            click.echo(f"❌ Server '{server_id}' not found")
            return

        # Get health check
        health = asyncio.run(registry.health_check(server_id))

        click.echo(f"📊 Status for MCP server '{server.name}' ({server_id}):")
        click.echo(f"   Server Status: {server.status.value}")
        click.echo(f"   Health Status: {health.get('status', 'unknown')}")

        if health.get("process_id"):
            click.echo(f"   Process ID: {health['process_id']}")

        if health.get("uptime"):
            uptime = int(health["uptime"])
            click.echo(f"   Uptime: {uptime} seconds")

        click.echo(f"   Endpoints: {server.endpoint_count}")
        click.echo(f"   Tools: {server.tool_count}")
        click.echo(f"   Complexity: {server.complexity_score:.2f}")
        click.echo(f"   Created: {server.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        click.echo(f"   Updated: {server.updated_at.strftime('%Y-%m-%d %H:%M:%S')}")

        if server.server_path:
            click.echo(f"   Path: {server.server_path}")

    except Exception as e:
        click.echo(f"❌ Failed to get server status: {e}")


@mcp.command("delete")
@click.argument("server_id")
@click.option("--keep-files", is_flag=True, help="Keep generated files")
def delete_server(server_id: str, keep_files: bool):
    """Delete a registered MCP server."""
    try:
        import asyncio

        from mcp.registry import MCPServerRegistry

        registry = MCPServerRegistry()

        # Get server info for confirmation
        server = registry.get_server(server_id)
        if not server:
            click.echo(f"❌ Server '{server_id}' not found")
            return

        # Confirm deletion
        if not click.confirm(f"Delete server '{server.name}' ({server_id})?"):
            click.echo("❌ Deletion cancelled")
            return

        click.echo(f"🗑️  Deleting MCP server '{server_id}'...")
        success = asyncio.run(
            registry.delete_server(server_id, cleanup_files=not keep_files)
        )

        if success:
            if keep_files:
                click.echo(f"✅ Server '{server_id}' deleted (files preserved)")
            else:
                click.echo(f"✅ Server '{server_id}' deleted completely")
        else:
            click.echo(f"❌ Failed to delete server '{server_id}'")

    except Exception as e:
        click.echo(f"❌ Failed to delete server: {e}")


@cli.group()
def dev():
    """Development environment commands."""
    pass


@dev.command()
def start():
    """Start development environment with Docker."""
    click.echo("🚀 Starting development environment...")

    if os.path.exists("docker-compose.dev.yml"):
        os.system("docker-compose -f docker-compose.dev.yml up --build")
    else:
        click.echo("❌ docker-compose.dev.yml not found")


@dev.command()
def stop():
    """Stop development environment."""
    click.echo("🛑 Stopping development environment...")

    if os.path.exists("docker-compose.dev.yml"):
        os.system("docker-compose -f docker-compose.dev.yml down")
    else:
        click.echo("❌ docker-compose.dev.yml not found")


@cli.group()
def deploy():
    """Deployment commands."""
    pass


@deploy.command()
@click.option(
    "--environment",
    "-e",
    default="development",
    type=click.Choice(["development", "staging", "production"]),
)
def k8s(environment: str):
    """Deploy to Kubernetes."""
    click.echo(f"🚀 Deploying to {environment}...")

    if environment == "production":
        if not click.confirm("Are you sure you want to deploy to production?"):
            return

    # TODO: Implement Kubernetes deployment
    click.echo(f"✅ Would deploy to {environment} environment")


@cli.command()
def init():
    """Initialize a new enterprise agents project."""
    click.echo("🏗️  Initializing OpenAI Agents Enterprise project...")

    # Create directory structure
    directories = [
        "agents",
        "mcp_servers",
        "config",
        "security",
        "models",
        "repositories",
        "auth",
        "audit",
        "monitoring",
        "tests",
        "docs",
    ]

    for directory in directories:
        Path(directory).mkdir(exist_ok=True)
        click.echo(f"📁 Created directory: {directory}")

    # Create basic configuration files
    config_template = """
# OpenAI Agents Enterprise Configuration
ENVIRONMENT=development
DEBUG=true
OPENAI_API_KEY=your-api-key-here
DATABASE_URL=postgresql://user:pass@localhost:5432/agents_dev
REDIS_URL=redis://localhost:6379
CREDENTIAL_ENCRYPTION_KEY=change-this-in-production
"""

    with open(".env.example", "w") as f:
        f.write(config_template)

    click.echo("✅ Project initialized successfully!")
    click.echo("📋 Next steps:")
    click.echo("   1. Copy .env.example to .env and configure your settings")
    click.echo("   2. Run 'agent_cli.py dev start' to start development environment")
    click.echo(
        "   3. Create your first agent with 'agent_cli.py agent create " "MyAgent'"
    )


if __name__ == "__main__":
    cli()
